### PR TITLE
T222560: Reduce overly verbose error output from Chameleon

### PR DESCRIPTION
**Pull request by viktordick**

### CODE REVIEW

**Review by gandie — APPROVED** [review]
mighty fine, lgtm

**Comment by viktordick** [comment]
Thanks @gandie.
@creakings Could you also have a look here? Since this is security relevant, you should also take a look.

**Comment by viktordick** [comment]
Actually, I just noticed that the second case with `PTRuntimeError` is not really necessary. Because this error is not handled explicitly in our `standard_error_message_parse`, it will only show a generic error message to the client if the system is marked as production system.

The first case was more important because it also handled `AssertionError`s where we pass the `error_value` to the client.

**Comment by viktordick** [comment]
That being said, I still think that even on a development system the `error_value` should be compact. The original `error_value` is also included in the `error_tb`, so we do not loose information, but the error page becomes easier to watch (short `error_value`, long `error_tb`)

**Review by creakings — APPROVED** [review]
LGTM

**Review by jan-jockusch — COMMENTED** [review]
LGTM!

**Pull request merged**
